### ISSUE TITLE
FastAPI CORS (Cross-Origin Resource Sharing)

### ISSUE THREAD

**Issue by Anim12** [pritishpattanaik/helpdesk-fastapi#5]
### About

[CORS or "Cross-Origin Resource Sharing"] refers to the situations when a frontend running in a browser has JavaScript code that communicates with a backend, and the backend is in a different "origin" than the frontend.

An origin is the combination of protocol (http, https), domain

So, let's say you have a frontend running in your browser at http://localhost:8080, and its JavaScript is trying to communicate with a backend running at http://localhost (because we don't specify a port, the browser will assume the default port 80).

Then, the browser will send an HTTP OPTIONS request to the backend, and if the backend sends the appropriate headers authorizing the communication from this different origin (http://localhost:8080) then the browser will let the JavaScript in the frontend send its request to the backend.

To achieve this, the backend must have a list of "allowed origins".

If this is not present then request might throw error saying status CORS.

**Comment by pritishpattanaik** [comment]
we need to either handle it in API gateway or directly in fastapi.
